name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史以读取所有 tag

      - name: Generate semantic version number
        id: version
        run: |
          # 获取仓库中最新 v*.*.* tag
          LAST_TAG=$(git tag --list "v*.*.*" --sort=-v:refname | head -n 1)
          if [ -z "$LAST_TAG" ]; then
            VERSION="1.0.0"
          else
            # 去掉前缀 v
            LAST_TAG=${LAST_TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LAST_TAG"

            PATCH=$((PATCH + 1))
            if [ $PATCH -gt 9 ]; then
              PATCH=0
              MINOR=$((MINOR + 1))
              if [ $MINOR -gt 9 ]; then
                MINOR=0
                MAJOR=$((MAJOR + 1))
              fi
            fi
            VERSION="$MAJOR.$MINOR.$PATCH"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "生成的版本号: $VERSION"

      - name: Compile
        run: make

      - name: Rename IPA with version
        run: |
          IPA_NAME="App-v${{ env.VERSION }}.ipa"
          mv APP.ipa "$IPA_NAME"
          echo "IPA_FILE=$IPA_NAME" >> $GITHUB_ENV

      - name: Set tag
        run: |
          TAG="v${{ env.VERSION }}"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          echo "生成的 tag: $TAG"

      - name: Create Release and Upload IPA
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.IPA_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}