name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史，确保能读取所有 tag

      - name: Generate version number from tags
        id: version
        run: |
          # 获取已有 v1.0.* 标签，按版本排序取最大
          LAST_TAG=$(git tag --list "v1.0.*" --sort=-v:refname | head -n 1)
          if [ -z "$LAST_TAG" ]; then
            VERSION="1.0.0"
          else
            PATCH=$(echo $LAST_TAG | awk -F. '{print $3}')
            PATCH=$((PATCH + 1))
            VERSION="1.0.$PATCH"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "自动生成版本号: $VERSION"

      - name: Compile
        run: make

      - name: Rename IPA with version
        run: |
          IPA_NAME="App-v${{ env.VERSION }}.ipa"
          mv APP.ipa "$IPA_NAME"
          echo "IPA_FILE=$IPA_NAME" >> $GITHUB_ENV

      - name: Set tag
        id: tag
        run: |
          TAG="v${{ env.VERSION }}"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          echo "生成的 tag: $TAG"

      - name: Create Release and Upload IPA
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.IPA_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}